### ISSUE TITLE
WhatIfIToldYou fails to load the PNG template

### ISSUE THREAD

**Issue by madhead** [madhead/ImgMacroBot#13]
The error in the logs:

```
Feb 20 00:25:14 bots ImgMacroBot[109364]: 2021-02-20T00:25:14,613 [ERROR] [eventLoopGroupProxy-4-1] [m.m.i.c.ImageMacroGenerationPipeline]: WhatIfIToldYou failed!
Feb 20 00:25:14 bots ImgMacroBot[109364]: java.lang.RuntimeException: Can't wrap nullptr
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.impl.Native.<init>(Native.java:13) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.Image.<init>(Image.java:143) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at org.jetbrains.skija.Image.makeFromEncoded(Image.java:15) ~[skija-shared-0.89.18.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at me.madhead.imgmacrobot.core.generators.WhatIfIToldYou.generate(WhatIfIToldYou.kt:67) ~[ImgMacroBot-core.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at me.madhead.imgmacrobot.core.generators.WhatIfIToldYou.generate(WhatIfIToldYou.kt:42) ~[ImgMacroBot-core.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at me.madhead.imgmacrobot.core.ParsingImageMacroGenerator$DefaultImpls.generate(ParsingImageMacroGenerator.kt:26) ~[ImgMacroBot-core.jar:?]
Feb 20 00:25:14 bots ImgMacroBot[109364]:         at me.madhead.imgmacrobot.core.generators.WhatIfIToldYou.generate(WhatIfIToldYou.kt:42) ~[ImgMacroBot-core.jar:?]
```

**Comment by madhead** [comment]
It seems that GH Actions have not checked out LFS files properly. The issue could be probably fixed by configuring LFS in `actions/checkout` in the release / deployment workflow.
